/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.android.apidemos.java.common;

// Meters, ValueWithUnitsTemplate are in the same package.
// UnitUtils is also in the same package.

public final class ImperialUnitsConverter extends UnitsConverter {
    public static final ImperialUnitsConverter INSTANCE = new ImperialUnitsConverter();
    // Placeholders for R.string resources. These would typically be generated by Android build tools.
    private static final int R_STRING_IN_FEET = 0x7f080001; // Example placeholder
    private static final int R_STRING_IN_MILES = 0x7f080002; // Example placeholder

    private ImperialUnitsConverter() {}

    @Override
    public ValueWithUnitsTemplate toDistanceUnits(Meters meters) {
        // Equivalent to: if (meters < 0.25.miles)
        // 0.25 miles in meters = 0.25 / MILES_PER_METER
        if (meters.getValue() < (0.25 / UnitUtils.MILES_PER_METER)) {
            return new ValueWithUnitsTemplate(meters.toFeet(), R_STRING_IN_FEET);
        } else {
            return new ValueWithUnitsTemplate(meters.toMiles(), R_STRING_IN_MILES);
        }
    }

    @Override
    public ValueWithUnitsTemplate toElevationUnits(Meters meters) {
        return new ValueWithUnitsTemplate(meters.toFeet(), R_STRING_IN_FEET);
    }
}
